### ISSUE TITLE
Seznam repo

### ISSUE THREAD

**Issue by vencax** [pirati-cz/angular-jekyll-editor#1]
na začátku vybrat github repo (např. select boxem), se kterým se bude pracovat? Tedy abych v konfiguraci neuváděl jen jeden repozitář, ale nějaký seznam

**Comment by stanley89** [comment]
Jak to vypadá prosím? Celkem by se tahle featura hodila :-)

**Comment by vencax** [comment]
Done (https://github.com/otevrenamesta/angular-jekyll-editor/tree/0.0.2), feedback welcommed :)
